application: php-teamwork-softuni
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: .*/css
  static_dir: website/css

- url: .*/img/
  static_dir: website/img

#- url: .*/server/config.php
#  script: website/server/config.php
  
- url: .*/about
  script: website/about.php
  

- url: /.*
  script: website/index.php