application: php-teamwork-softuni
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: .*/css
  static_dir: website/css

- url: .*/img/
  static_dir: website/img

- url: .*/script
  static_dir: website/script

#- url: .*/server/config.php
#  script: website/server/config.php
- url: .*/error
  script: website/error.php

- url: .*/regpage
  script: website/regpage.php

- url: .*/add_img
  script: website/add_img.php

- url: .*/user
  script: website/user.php

- url: .*/about
  script: website/about.php

- url: .*/logout
  script: website/logout.php

- url: /.*
  script: website/index.php